server.port=8084
spring.application.name=transfer-service

spring.data.mongodb.uri=mongodb://localhost:27017/remetym_transfer

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

services.inventory.url=http://localhost:8083/api/inventory
services.notification.url=http://localhost:8085/api/notifications
